In [1]:
import numpy as np

In [4]:
data = {i: np.random.randn() for i in range(7)}
data

{0: 0.4571150851539559,
 1: -0.3044747125443518,
 2: 1.1805838971778366,
 3: -0.6577024855080722,
 4: 0.4051604940389793,
 5: -0.06642109471446454,
 6: -2.471158918230118}

In [9]:
from numpy.random import randn
data = {i: randn() for i in range(7)}
data

{0: -1.0205440233444922,
 1: -0.4617415794451413,
 2: 1.073246485965654,
 3: 0.17531535140144902,
 4: 0.8042301901342297,
 5: 0.1757885559325626,
 6: 1.6773872692870622}

In [10]:
# numpy 자료형 정리
# x = 365
# scalar 값
# rank =0

In [11]:
# x = [1,2,3,4]
# vector 값
# rank =1
#shape=(4,)

In [12]:
# x = [[1,2,3], [4,5,6]]
# mattrix 행렬
# rank =2
#shape=(행,열) / (2,3)

In [14]:
# x = [[[.....]]]
# cube, 3D
# rank =3
#shape=(X,Y,Z)

In [17]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.shape

(3,)

In [24]:
a[0], a[2]

(1, 3)

In [25]:
a[0]=5 #값 변경

In [28]:
a

array([5, 2, 3])

In [29]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
type(b)

numpy.ndarray

In [31]:
b.shape

(2, 3)

In [35]:
b[1,1], b[1,2]

(5, 6)

In [36]:
c = np.arange(32)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [37]:
c = np.arange(32).reshape(8,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [39]:
a = np.zeros((2,2)) # 모든 값이 0인 배열 생성
print(a)

[[0. 0.]
 [0. 0.]]


In [41]:
b = np.ones((1,2)) # 모든 값이 1인 배열 생성
print(b)

[[1. 1.]]


In [42]:
c = np.full((2,2),7) # 모든 값이 특정 상수인 배열 생성
print(c)

[[7 7]
 [7 7]]


In [43]:
d = np.eye(2) # 2X2 단위 행렬 생성 대각선은 1이고 나머지는 0인 행렬
print(d)

[[1. 0.]
 [0. 1.]]


In [44]:
e = np.random.random((2,2)) #임의의 값으로 채워진 배열 생성
print(e)

[[0.33216728 0.38866042]
 [0.09703971 0.15218443]]


In [46]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [51]:
# 원본 배열을 계속 해서 참조 하고 있다.
b[0,0] = 77
a[0,1] #b의 값을 바꿔서 a의 값까지 같이 바뀐다.
# 따로 쓰고 싶다면 .copy를 이용한다.
c = a[:2, 1:3].copy()
print(c)
c[0,0] = 11
a[0,1] #a값은 바뀌지 않는다.

[[77  3]
 [ 6  7]]


77

In [53]:
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m[1,:]) # index로 짜르면 rank가 줄어든다
print(m[1:2,:]) # 슬라이싱으로 짜르면 rank는 유지된다.

[5 6 7 8]
[[5 6 7 8]]


In [59]:
y = np.array([[1,2],[3,4],[5,6]])
bool_idx = (y >2)
print(bool_idx)
print(y[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [57]:
print(y[y>2])

[3 4 5 6]


In [61]:
m.dtype

dtype('int32')

In [63]:
x = np.array([1., 2.])
x.dtype

dtype('float64')

In [64]:
x = np.array([1., 2.], dtype=np.int64)
x.dtype

dtype('int64')

In [70]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(y))
print(np.dot(x,y))
print(x*y) #이거와 다름

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [73]:
r = np.array([[1,2],[3,4]])
print(np.sum(r))
print(np.sum(r, axis=0))
print(np.sum(r, axis=1))

10
[4 6]
[3 7]


In [77]:
# 그외 함수 http://docs.scipy.org/doc/numpy/reference/routines.math.html
print(np.max(r))
print(np.argmax(r))

4
3


In [79]:
print(np.min(r))
print(np.argmin(r))

1
0


In [76]:
print(np.mean(r))

2.5


In [81]:
r.T #전치행렬(행과 열의 index값을 바꾼다.)

array([[1, 3],
       [2, 4]])

In [84]:
ee = np.array([[1,2],[3,4],[5,6],[7,8]])
print(ee)
print(ee.T)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 3 5 7]
 [2 4 6 8]]
